import type {
  IMilestone,
  IStatItem,
  ITimelineMilestone,
  IValuePillar,
} from '../model/studio'
import {
  COMPANY_TIMELINE as STATIC_COMPANY_TIMELINE,
  HERO_STATS as STATIC_HERO_STATS,
  MILESTONES as STATIC_MILESTONES,
  SEPARATOR_STATS as STATIC_SEPARATOR_STATS,
  STUDIO_STATS as STATIC_STUDIO_STATS,
  TIMELINE_MILESTONES as STATIC_TIMELINE_MILESTONES,
  VALUE_PILLARS as STATIC_VALUE_PILLARS,
} from '../infrastructure/static/studio'

export const COMPANY_TIMELINE = STATIC_COMPANY_TIMELINE
export const HERO_STATS: IStatItem[] = STATIC_HERO_STATS
export const MILESTONES: IMilestone[] = STATIC_MILESTONES
export const SEPARATOR_STATS: IStatItem[] = STATIC_SEPARATOR_STATS
export const STUDIO_STATS: IStatItem[] = STATIC_STUDIO_STATS
export const TIMELINE_MILESTONES: ITimelineMilestone[] = STATIC_TIMELINE_MILESTONES
export const VALUE_PILLARS: IValuePillar[] = STATIC_VALUE_PILLARS
